---
- name: Install and configure MariaDB (LAMP project)
  hosts: db
  become: yes
  vars:
    mysql_root_password: ""
    app_db_name: lampdb
    app_db_user: lampuser
    app_db_password: lamppass
    mariadb_conf_file: /etc/my.cnf.d/mariadb-server.cnf

  tasks:

    - name: Install MariaDB server
      ansible.builtin.dnf:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB listens on all interfaces (bind-address = 0.0.0.0)
      ansible.builtin.lineinfile:
        path: "{{ mariadb_conf_file }}"
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        insertafter: '^\[mysqld\]'
        backup: yes
      notify: restart mariadb

    - name: Start and enable MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create application database
      ansible.builtin.shell: >
        mysql -e "CREATE DATABASE IF NOT EXISTS {{ app_db_name }};"

    - name: Create application DB user and grant privileges
      ansible.builtin.shell: |
        mysql -e "
        CREATE USER IF NOT EXISTS '{{ app_db_user }}'@'%' IDENTIFIED BY '{{ app_db_password }}';
        GRANT ALL PRIVILEGES ON {{ app_db_name }}.* TO '{{ app_db_user }}'@'%';
        FLUSH PRIVILEGES;"

  handlers:
    - name: restart mariadb
      ansible.builtin.service:
        name: mariadb
        state: restarted
