---
- name: Rollback database changes (CentOS/RHEL)
  hosts: db
  become: yes
  tasks:
    - name: Remove MariaDB/MySQL packages
      ansible.builtin.dnf:
        name:
          - mariadb-server
          - mariadb
          - mysql-server
        state: absent
      ignore_errors: yes

    - name: Remove MySQL data directory (optional)
      ansible.builtin.file:
        path: /var/lib/mysql
        state: absent
      ignore_errors: yes


- name: Rollback LAMP changes on webservers (CentOS/RHEL)
  hosts: 192.168.100.152
  become: yes
  tasks:
    - name: Remove Apache and PHP packages
      ansible.builtin.dnf:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-cli
          - php-fpm
        state: absent
      ignore_errors: yes

    - name: Clean up leftover web files
      ansible.builtin.file:
        path: /var/www/html/
        state: absent
      ignore_errors: yes
