---
- hosts: controller
  become: yes
  tasks:
    - name: Let's install Rancher storage provider
      ansible.builtin.command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.32/deploy/local-path-storage.yaml

    - name: Mark local-path StorageClass as default
      ansible.builtin.command:
        cmd: "kubectl patch storageclass local-path -p '{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}'"
