---
- name: Install httpd and start the service
  hosts: eoc-node1
  become: yes
  tasks:
    - name: Install the required package
      ansible.builtin.dnf:
        name: "{{ ansible_facts.ansible_local.custom.general.package }}"
        state: latest
    - name: Start the service with parameters from custom facts
      ansible.builtin.service:
        name: "{{ ansible_facts.ansible_local.custom.general.service }}"
        state: "{{ ansible_facts.ansible_local.custom.general.state }}"
        enabled: "{{ ansible_facts.ansible_local.custom.general.enabled }}"
