---
- name: Demo job with Fedora EE 
  hosts: 192.168.100.150
  become: yes
  tasks:
    - name: Install nginx via apt
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Ensure nginx is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Served by Fedora EE via AWX & Ansible on centos!</h1>
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Show Ansible version inside EE
      ansible.builtin.command: ansible --version
