---
- name: "Deploying LAMP Stack"
  hosts: webservers
  become: yes
  tasks:
    - name: "Install Latest Packages"
      ansible.builtin.dnf:
        name:
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
          - firewalld
        state: latest
    - name: "Copy contents"
      ansible.builtin.copy:
        content: "Test LAMP Stack"
        dest: /var/www/html/index.html
    - name: "Enable and Start HTTPD Service"
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: "Enable and Start MYSQL Service"
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
    - name: "Enable and Start Firewalld Service"
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
    - name: "Add exception in the firewall"
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

- name: Test page
  hosts: localhost
  tasks:
    - name: acces page
      uri:
        url: http://eoc-node3
        status_code: 200
