---
- name: Use the fetch module to retrieve secure log files
  hosts: all
  become: yes
  tasks:
    - name: Fetch the /var/log/secure log file from managed hosts
      ansible.builtin.fetch:
        src: /var/log/secure
        dest: secure-backups
        flat: no
